package com.pawpark.backend.model;

public enum Raza {

    AMERICAN_STAFFORDSHIRE_TERRIER,
    BODEGUERO_ANDALUZ,
    BULL_TERRIER,
    STAFFORDSHIRE_BULL_TERRIER,
    JACK_RUSSELL_TERRIER,
    YORKSHIRE_TERRIER,
    PITBULL_TERRIER,

    PASTOR_ALEMAN,
    PASTOR_BELGA_MALINOIS,
    PASTOR_AUSTRALIANO,
    BORDER_COLLIE,
    ROTTWEILER,
    DOBERMAN,
    BOXER,
    CANICHE,

    GALGO,
    PODENCO,
    BEAGLE,
    COCKER_SPANIEL,
    SETTER_IRLANDES,
    BRETON,
    TECKEL,
    DACSHUND,

    CANE_CORSO,
    GOLDEN_RETRIEVER,
    LABRADOR_RETRIEVER,
    MASTIN_ESPANOL,
    DOGO_ALEMAN,
    DOGO_ARGENTINO,
    SAN_BERNARDO,
    AKITA_INU,

    BICHON_MALTES,
    BULLDOG_FRANCES,
    BULLDOG_INGLES,
    CHIHUAHUA,
    PUG_CARLINO,
    SHIBA_INU,
    POMERANIA,
    SHIH_TZU,

    PERRO_DE_AGUA,
    MESTIZO,
    OTRA_RAZA
}
