# CONFIGURACIÓN DEL SERVIDOR
# Puerto de la base de datos local
# server.port=8081
# http://localhost:8081/swagger-ui/index.html

# Puerto para servidor en la nube Railway
# Railway asigna el puerto dinámicamente, esto es obligatorio para que funcione
server.port=${PORT:8081}


# NOMBRE DE LA APLICACIÓN (Útil para Swagger)
spring.application.name=PawParkBackend
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# 1. Database Connection Settings
# Usaremos variables que Railway nos dará automáticamente, si no la detecta, se conectará a nuestra BD local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_pawpark?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'update': Crea/actualiza las tablas automáticamente al iniciar
# Mantenemos 'update' para que Railway cree las tablas solo al subir el código
spring.jpa.hibernate.ddl-auto=update
# Mostrar las consultas SQL en la consola (útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Añadimos estas dos líneas para permitir archivos de hasta 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB